"use strict";

try {
  require("dotenv").config();
} catch {}

const fs = require("fs");
const path = require("path");

const catalystDir = process.env.CATALYST_DIR || path.resolve(__dirname, "..");
const templatePath = path.join(catalystDir, "templates/iSteel_Proposal_Site.html");
const targetPath = path.join(catalystDir, "slate/spikra-experience/index.html");
const builderPath = path.join(catalystDir, "scripts/build_slate_index.js");

let templateContent = fs.readFileSync(templatePath, "utf8");

templateContent = templateContent.replace(
  /<title>[\s\S]*?<\/title>/i,
  '<title id="spikra-page-title">Proposal Experience</title>'
);

const headScript = [
  '<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">',
  '<meta http-equiv="Pragma" content="no-cache">',
  '<meta http-equiv="Expires" content="0">',
  '<link rel="icon" type="image/x-icon" href="/favicon.ico">',
  '<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">',
  '<link rel="icon" type="image/png" href="/favicon.png">',
  '<script>',
  '(function() {',
  '  var path = window.location.pathname || "";',
  '  var slug = path.replace(new RegExp("^/+|/+$", "g"), "").trim();',
  '  var isRoot = (!slug || slug.toLowerCase() === "index.html");',
  '  var params = new URLSearchParams(window.location.search);',
  '  var expId = params.get("experience_id") || params.get("id") || "";',
  '  var querySlug = params.get("slug") || "";',
  '',
  '  if (isRoot && !expId && !querySlug) {',
  '    document.title = "iSteel (VIPL) \u00B7 Zoho CRM & Marketing Automation | Spikra";',
  '    return;',
  '  }',
  '',
  '  var rawSlug = (!isRoot ? slug : querySlug) || "";',
  '  var cleanName = rawSlug.replace(/_proposal$/i, "").replace(new RegExp("[-_]+", "g"), " ").trim();',
  '  if (cleanName) {',
  '    var businessName = cleanName.split(" ").map(function(w) {',
  '      if (w.toLowerCase() === "and" || w.toLowerCase() === "of" || w.toLowerCase() === "the") return w.toLowerCase();',
  '      if (w.length <= 2) return w.toUpperCase();',
  '      return w.charAt(0).toUpperCase() + w.slice(1).toLowerCase();',
  '    }).join(" ");',
  '    document.title = businessName;',
  '  } else {',
  '    document.title = "Proposal Experience";',
  '  }',
  '',
  '  document.write("<style id=\\"spikra-experience-styles\\">" +',
  '    "#spikra-default-root { display: none !important; } " +',
  '    "#spikra-loader-screen { display: flex; } " +',
  '    "html, body { background: #f8fafc !important; margin: 0; padding: 0; }" +',
  '    "</style>");',
  '',
  '  var DEPLOY_ENDPOINT = "https://spikra-ai-proposal-698386704.development.catalystserverless.com/spikra/experience/deploy";',
  '  var activeSlug = (!isRoot) ? slug : querySlug;',
  '  var targetUrl = DEPLOY_ENDPOINT;',
  '  if (activeSlug) {',
  '    targetUrl += "?slug=" + encodeURIComponent(activeSlug);',
  '    if (expId) targetUrl += "&experience_id=" + encodeURIComponent(expId);',
  '  } else if (expId) {',
  '    targetUrl += "?experience_id=" + encodeURIComponent(expId);',
  '  }',
  '  if (params.get("project_id")) {',
  '    targetUrl += (targetUrl.indexOf("?") >= 0 ? "&" : "?") + "project_id=" + encodeURIComponent(params.get("project_id"));',
  '  }',
  '',
  '  window.__spikraTargetUrl = targetUrl;',
  '  window.__spikraActiveSlug = activeSlug || "";',
  '',
  '  var controller = (typeof AbortController !== "undefined") ? new AbortController() : null;',
  '  var timeoutId = controller ? setTimeout(function() { controller.abort(); }, 14000) : null;',
  '',
  '  window.__spikraProposalFetch = fetch(targetUrl, { signal: controller ? controller.signal : undefined })',
  '    .then(function(res) {',
  '      if (timeoutId) clearTimeout(timeoutId);',
  '      return res.text().then(function(html) {',
  '        return { ok: res.ok, status: res.status, html: html };',
  '      });',
  '    })',
  '    .catch(function(err) {',
  '      if (timeoutId) clearTimeout(timeoutId);',
  '      var isTimeout = err && (err.name === "AbortError" || err.message === "The user aborted a request.");',
  '      return {',
  '        ok: false,',
  '        status: isTimeout ? 408 : 0,',
  '        error: isTimeout ? "Loading proposal timed out after 14 seconds" : (err.message || "Network connection failed")',
  '      };',
  '    });',
  '})();',
  '</script>'
].join("\n");

templateContent = templateContent.replace("<head>", "<head>\n" + headScript);

const bodyOpenIdx = templateContent.indexOf("<body>");
const bodyCloseIdx = templateContent.lastIndexOf("</body>");

const beforeBody = templateContent.substring(0, bodyOpenIdx + 6);
const innerBody = templateContent.substring(bodyOpenIdx + 6, bodyCloseIdx);
const afterBody = templateContent.substring(bodyCloseIdx);

const topOrbitalLoader = [
  '<!-- Spikra Orbital Loading Screen (Rendered immediately on first frame for proposal routes) -->',
  '<div id="spikra-loader-screen" style="position:fixed;inset:0;background:#f8fafc;display:none;flex-direction:column;align-items:center;justify-content:center;z-index:99999;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,sans-serif;color:#0c2c3e;padding:24px;">',
  '  <div style="position:relative;width:64px;height:64px;margin-bottom:20px;">',
  '    <div style="position:absolute;inset:0;border:2.5px solid transparent;border-top-color:#F4611F;border-radius:50%;animation:spikra-orbit-cw 1s linear infinite;"></div>',
  '    <div style="position:absolute;inset:8px;border:2.5px solid transparent;border-top-color:#2C7CB8;border-radius:50%;animation:spikra-orbit-ccw 1.5s linear infinite;"></div>',
  '    <div style="position:absolute;inset:16px;border:2px solid transparent;border-top-color:#0C2C3E;border-radius:50%;animation:spikra-orbit-cw 0.8s linear infinite;"></div>',
  '  </div>',
  '  <div id="spikra-loader-title" style="font-size:17px;font-weight:600;letter-spacing:-0.01em;color:#0c2c3e;margin-bottom:6px;">Loading Proposal Experience</div>',
  '  <div id="spikra-loader-sub" style="font-size:13.5px;color:#6B7C87;transition:all 0.3s ease;">Preparing personalized presentation\u2026</div>',
  '  <div id="spikra-loader-fallback-prompt" style="display:none;margin-top:24px;text-align:center;font-size:13px;color:#64748b;">',
  '    Taking longer than usual? <a id="spikra-direct-link" href="#" target="_blank" rel="noopener" style="color:#f4611f;font-weight:600;text-decoration:underline;margin-left:4px;">Open Direct View \u2197</a>',
  '  </div>',
  '  <style>',
  '    @keyframes spikra-orbit-cw { to { transform: rotate(360deg); } }',
  '    @keyframes spikra-orbit-ccw { to { transform: rotate(-360deg); } }',
  '  </style>',
  '</div>'
].join("\n");

const bottomScript = [
  '<script>',
  '(function() {',
  '  if (!window.__spikraProposalFetch) {',
  '    return;',
  '  }',
  '',
  '  var targetUrl = window.__spikraTargetUrl || "https://spikra-ai-proposal-698386704.development.catalystserverless.com/spikra/experience/deploy";',
  '  var activeSlug = window.__spikraActiveSlug || "";',
  '',
  '  var subElem = document.getElementById("spikra-loader-sub");',
  '  var promptElem = document.getElementById("spikra-loader-fallback-prompt");',
  '  var directLinkElem = document.getElementById("spikra-direct-link");',
  '  if (directLinkElem) directLinkElem.href = targetUrl;',
  '',
  '  var t1 = setTimeout(function() {',
  '    if (subElem) subElem.textContent = "Connecting to secure proposal server\u2026";',
  '  }, 2500);',
  '',
  '  var t2 = setTimeout(function() {',
  '    if (subElem) subElem.textContent = "Rendering proposal layout and components\u2026";',
  '  }, 5000);',
  '',
  '  var t3 = setTimeout(function() {',
  '    if (promptElem) promptElem.style.display = "block";',
  '  }, 7500);',
  '',
  '  function clearProgressTimers() {',
  '    clearTimeout(t1);',
  '    clearTimeout(t2);',
  '    clearTimeout(t3);',
  '  }',
  '',
  '  var isLoaderDismissed = false;',
  '  function hideLoader() {',
  '    if (isLoaderDismissed) return;',
  '    isLoaderDismissed = true;',
  '    clearProgressTimers();',
  '',
  '    var styleTag = document.getElementById("spikra-experience-styles");',
  '    if (styleTag && styleTag.parentNode) {',
  '      styleTag.parentNode.removeChild(styleTag);',
  '    }',
  '    var loader = document.getElementById("spikra-loader-screen");',
  '    if (loader) {',
  '      loader.style.setProperty("display", "none", "important");',
  '      if (loader.parentNode) {',
  '        loader.parentNode.removeChild(loader);',
  '      }',
  '    }',
  '    var defaultRoot = document.getElementById("spikra-default-root");',
  '    if (defaultRoot) {',
  '      defaultRoot.style.setProperty("display", "none", "important");',
  '    }',
  '    var frame = document.getElementById("spikra-proposal-frame");',
  '    if (frame) {',
  '      frame.style.setProperty("z-index", "2147483647", "important");',
  '      frame.style.setProperty("display", "block", "important");',
  '    }',
  '  }',
  '',
  '  window.hideSpikraLoader = hideLoader;',
  '',
  '  function showErrorInUI(title, message, statusCode) {',
  '    clearProgressTimers();',
  '    var styleTag = document.getElementById("spikra-experience-styles");',
  '    if (styleTag && styleTag.parentNode) {',
  '      styleTag.parentNode.removeChild(styleTag);',
  '    }',
  '    var loader = document.getElementById("spikra-loader-screen");',
  '    if (!loader) {',
  '      loader = document.createElement("div");',
  '      loader.id = "spikra-loader-screen";',
  '      document.body.appendChild(loader);',
  '    }',
  '',
  '    loader.style.cssText = "position:fixed;inset:0;background:#f8fafc;display:flex!important;flex-direction:column;align-items:center;justify-content:center;z-index:2147483647;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,sans-serif;color:#0c2c3e;padding:24px;box-sizing:border-box;";',
  '',
  '    var errorHtml = \'<div style="max-width:480px;width:100%;background:#ffffff;border:1px solid #fee2e2;border-radius:18px;box-shadow:0 12px 36px rgba(220,38,38,0.08),0 4px 12px rgba(12,44,62,0.04);padding:32px 28px;text-align:center;box-sizing:border-box;">\' +',
  '      \'<div style="width:56px;height:56px;border-radius:50%;background:#fef2f2;color:#ef4444;display:inline-flex;align-items:center;justify-content:center;font-size:26px;margin-bottom:16px;">\u26A0\uFE0F</div>\' +',
  '      \'<h2 style="font-size:19px;font-weight:700;color:#0f172a;margin:0 0 8px;letter-spacing:-0.01em;">\' + (title || "Proposal Not Available") + \'</h2>\' +',
  '      \'<p style="font-size:14px;color:#64748b;margin:0 0 16px;line-height:1.55;">\' + (message || "The requested proposal experience could not be loaded.") + \'</p>\' +',
  '      \'<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:10px 14px;font-size:12px;color:#475569;text-align:left;margin-bottom:20px;word-break:break-all;line-height:1.6;">\' +',
  '        \'<div><strong>Document Slug:</strong> \' + (activeSlug || "None specified") + \'</div>\' +',
  '        \'<div><strong>Status:</strong> \' + (statusCode ? ("HTTP " + statusCode) : "Connection issue") + \'</div>\' +',
  '      \'</div>\' +',
  '      \'<div style="display:flex;gap:12px;justify-content:center;flex-wrap:wrap;">\' +',
  '        \'<button onclick="window.location.reload()" style="padding:10px 22px;background:#0c2c3e;color:#ffffff;border:none;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;transition:background 0.2s;">Retry</button>\' +',
  '        \'<a href="\' + targetUrl + \'" target="_blank" rel="noopener" style="display:inline-flex;align-items:center;gap:4px;padding:10px 22px;background:#f4611f;color:#ffffff;text-decoration:none;border-radius:8px;font-size:13px;font-weight:600;transition:background 0.2s;">Open Direct View \u2197</a>\' +',
  '      \'</div>\' +',
  '    \'</div>\';',
  '',
  '    loader.innerHTML = errorHtml;',
  '  }',
  '',
  '  window.__spikraProposalFetch',
  '    .then(function(result) {',
  '      if (!result.ok || !result.html || result.status >= 400) {',
  '        var errorMsg = result.error || ("The server returned an error (HTTP " + (result.status || "unknown") + ").");',
  '        try {',
  '          var parsed = JSON.parse(result.html);',
  '          if (parsed && (parsed.message || parsed.error)) {',
  '            errorMsg = parsed.message || parsed.error;',
  '          }',
  '        } catch(e) {}',
  '        showErrorInUI("Unable to Load Proposal", errorMsg, result.status);',
  '        return;',
  '      }',
  '',
  '      var html = result.html;',
  '',
  '      if (html.trim().startsWith("{") && html.indexOf(\'"success":false\') !== -1) {',
  '        try {',
  '          var errObj = JSON.parse(html);',
  '          showErrorInUI("Proposal Unavailable", errObj.message || "This proposal could not be retrieved.", result.status);',
  '          return;',
  '        } catch(e) {}',
  '      }',
  '',
  '      var googleFontsLink = \'<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">\';',
  '      html = html',
  '        .replace(/\\$1\\s*(<link rel="stylesheet")/gi, googleFontsLink + "\\n$1")',
  '        .replace(/<link rel="preconnect" href="https:\\/\\/fonts\\.gstatic\\.com" crossorigin>\\s*\\$1/gi, \'<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\\n\' + googleFontsLink)',
  '        .replace(/^\\s*\\$1\\s*$/gm, "")',
  '        .replace(/>\\s*\\$1\\s*</g, "><");',
  '',
  '      if (html && html.indexOf("favicon") === -1) {',
  '        html = html.replace("<head>", \'<head><link rel="icon" type="image/x-icon" href="/favicon.ico">\');',
  '      }',
  '',
  '      var dismissScript = \'<script>try{if(window.parent&&window.parent.hideSpikraLoader){window.parent.hideSpikraLoader();}}catch(e){}<\\/script>\';',
  '      if (html.indexOf("</body>") !== -1) {',
  '        html = html.replace("</body>", dismissScript + "</body>");',
  '      } else {',
  '        html += dismissScript;',
  '      }',
  '',
  '      var frame = document.createElement("iframe");',
  '      frame.id = "spikra-proposal-frame";',
  '      frame.title = "Spikra Customer Proposal";',
  '      frame.style.cssText = "position:fixed;inset:0;width:100%;height:100%;border:none;margin:0;padding:0;z-index:2147483647;background:#f7f9fa;display:block;";',
  '      frame.setAttribute("allow", "fullscreen");',
  '',
  '      frame.onload = function() {',
  '        hideLoader();',
  '      };',
  '',
  '      document.body.appendChild(frame);',
  '      frame.srcdoc = html;',
  '',
  '      // Fast-acting watchdogs: ensure loader is dismissed once document is injected and ready',
  '      setTimeout(function() {',
  '        hideLoader();',
  '      }, 350);',
  '',
  '      setTimeout(function() {',
  '        hideLoader();',
  '      }, 1000);',
  '    })',
  '    .catch(function(err) {',
  '      showErrorInUI("Proposal Connection Error", err.message || "Could not connect to the proposal server.", 0);',
  '    });',
  '})();',
  '</script>'
].join("\n");

const finalHtml = beforeBody +
  topOrbitalLoader +
  '\n<div id="spikra-default-root">\n' +
  innerBody +
  '\n</div>\n' +
  bottomScript +
  afterBody;

fs.writeFileSync(targetPath, finalHtml, "utf8");
fs.writeFileSync(builderPath, fs.readFileSync(__filename, "utf8"), "utf8");
console.log("Successfully built " + targetPath + " and synced " + builderPath);
